### ISSUE TITLE
When the best intervention is not to intervene

### ISSUE THREAD

**Issue by sembrestels** [CommonsBuild/IH-intervention#1]
### 1. Does this proposal address that some categories may be under rewarded and others over rewarded?

No

### 2. Does this proposal address that paid contributors have had a 50-85% reduction to their total number of impact hours?

No

### 3. Does this proposal address that foundational members of the Token Engineering Community may lack recognition for their less visible work?

No

### 4. Does this proposal address the distribution of impact hours in relation to equality metrics such as the Gini Coefficient?

No

### What interventions are being proposed? 

I propose to not intervine, even aknowedging that some improvements have to be done to the praising system to track contributions in the future.

### What is the reasoning?

1. **Is retweeting over-rewarded?** For sure, but it was an easy entry point for many people, and at some point I guess it looked like a good idea to reward these kind of interactions. It is something easy for everyone to have some tokens and distribute the token among many people.
2. **Impact hour deductions:** At the very beinning it was uncertain that this project were going to succeed and many people took a high risk not being paid for their work. This project wouldn't have been possible without the paid contributors (I praise all of them for that!), but we (me included) have been paid for doing so, and we could choose not to be at any point during the project to be more exposed to IH. It looks unfair now to change the rules of the game at the end of the game. The same applies to governace power: the rules were clear from the beginning, and it has been a long process in which people could choose.
3. **Recognize TE work:** The whole TEC is made to recognize and reward TE work, although IH are made to reward initial contributors to build the commons infrastructure around TE. The whole purpose of the hatch and conviction voting is to fund TE work. After the hatch we can do lots of conviction voting proposals for converting funds from the common pool to TEC tokens in order to reward previous TE work.
4. **Impact Hour distribution equality:** Impact hours are earned hours. UBI can be useful to end extreme poverty, but we are not talking about poverty here. IH is a system to value and recognize contributions, and it would be against its purpose to value contributions without a real impact. Creating a community with a low gini coeficient would be great (it would mean that we have lots of engaged people producing lots of valuable things), but changing the gini coeficient artificially by redistributing the hardly earned rewards doesn't make it.

--- 

🤔 Take a look at [this forum post](https://forum.tecommons.org/t/pre-hatch-impact-hours-distribution-analysis/376/50?u=liviade) if you have any questions.

🗳 When you are finished writing, head over to [TokenLog](https://tokenlog.xyz/TECommons/TokenLog-SoftGov) and vote for your favourite proposals! 

📆 This voting session ends on Thursday, July 1 at 2pm EST / 8pm CET, the start of the weekly TEC Community Call.

**Comment by GriffGreen** [comment]
<a href="https://imgflip.com/i/5evs0m"><img src="https://i.imgflip.com/5evs0m.jpg" title="made at imgflip.com"/></a><div><a href="https://imgflip.com/memegenerator">from Imgflip Meme Generator</a></div>

**Comment by GriffGreen** [comment]
<a href="https://imgflip.com/i/5evs4m"><img src="https://i.imgflip.com/5evs4m.jpg" title="made at imgflip.com"/></a><div><a href="https://imgflip.com/memegenerator">from Imgflip Meme Generator</a></div>

**Comment by GriffGreen** [comment]
<a href="https://imgflip.com/i/5evsik"><img src="https://i.imgflip.com/5evsik.jpg" title="made at imgflip.com"/></a><div><a href="https://imgflip.com/memegenerator">from Imgflip Meme Generator</a></div>

**Comment by jessicazartler** [comment]
![image](https://user-images.githubusercontent.com/43972522/123822718-89b0f080-d8ca-11eb-86d1-a4a5c56ea1ab.png)

![eqyal](https://user-images.githubusercontent.com/43972522/123821731-a8fb4e00-d8c9-11eb-9b04-e500bb3a64f6.jpg)

**Comment by jessicazartler** [comment]
![image](https://user-images.githubusercontent.com/43972522/123823304-0e9c0a00-d8cb-11eb-9f38-c1ae4aaf1b37.png)

![slap](https://user-images.githubusercontent.com/43972522/123818951-63d61c80-d8c7-11eb-8c76-53c351225be2.jpg)

**Comment by jessicazartler** [comment]
![image](https://user-images.githubusercontent.com/43972522/123819101-836d4500-d8c7-11eb-8458-22a66be1807c.png)

**Comment by jessicazartler** [comment]
![yoda](https://user-images.githubusercontent.com/43972522/123819647-f080da80-d8c7-11eb-9fd8-83584ae513b2.jpg)

**Comment by jessicazartler** [comment]
![ubi-baby](https://user-images.githubusercontent.com/43972522/123819686-f7a7e880-d8c7-11eb-939f-feaf0910da71.jpg)

**Comment by jessicazartler** [comment]
![oprah](https://user-images.githubusercontent.com/43972522/123819787-08585e80-d8c8-11eb-87f3-8e0494254155.jpg)

**Comment by jessicazartler** [comment]
![fix-itself](https://user-images.githubusercontent.com/43972522/123819814-0ee6d600-d8c8-11eb-85e3-9018641aaa3b.jpg)

**Comment by jessicazartler** [comment]
![office jpg](https://user-images.githubusercontent.com/43972522/123819872-1ad29800-d8c8-11eb-999e-034f157f4b9a.jpg)

**Comment by jessicazartler** [comment]
![system](https://user-images.githubusercontent.com/43972522/123819890-21610f80-d8c8-11eb-8a89-453116c8d6d7.jpg)

**Comment by jessicazartler** [comment]
![Draw-25](https://user-images.githubusercontent.com/43972522/123820090-4ce3fa00-d8c8-11eb-8f0f-5ace3b6a8865.jpg)

**Comment by jessicazartler** [comment]
![share](https://user-images.githubusercontent.com/43972522/123820105-4fdeea80-d8c8-11eb-832d-d4266ba811d8.jpg)

**Comment by jessicazartler** [comment]
![Whoa](https://user-images.githubusercontent.com/43972522/123820120-52d9db00-d8c8-11eb-9fc9-815599068a2f.jpg)

**Comment by jessicazartler** [comment]
![Skeleton](https://user-images.githubusercontent.com/43972522/123820137-566d6200-d8c8-11eb-8f92-24c505a621fd.jpg)

**Comment by sembrestels** [comment]
![gtnw](https://user-images.githubusercontent.com/931684/123851436-78dc9b00-d91b-11eb-83da-427082c29580.jpg)

**Comment by jessicazartler** [comment]
![image](https://user-images.githubusercontent.com/43972522/123883577-55175600-d917-11eb-84c8-f2b8c431c7d6.png)

**Comment by jessicazartler** [comment]
> [![](https://camo.githubusercontent.com/c3f9059fe41d66f0c348c19d6c526d3aed2d17b63390ba0c03280f80f95ffa27/68747470733a2f2f692e696d67666c69702e636f6d2f35657673696b2e6a7067)](https://imgflip.com/i/5evsik)
> 
> [from Imgflip Meme Generator](https://imgflip.com/memegenerator)

Yes, proposal #1 (this one) and #2 are a no. Vote for #3 or #4!!! :D

**Comment by MrsBadgerface** [comment]
Hey @sembrestels When I read this, I hear a strong sense of what you see as a just and equitable space (not changing the rules partway through; we spent time on decisions and those decisions should be upheld) and while it's not a position that I am able to support, I wanted to acknowledge what's just and equitable for you.

**Comment by sembrestels** [comment]
If you ask me, I don't think the current system is fair. If I could go back to the past I would not agree on many things on the current praise system.

The problem is that I don't believe that there is a solution that would be fair for everyone at this point. This is why I personally think it is better not to intervene with a top-to-down solution.

**Comment by danelsuga** [comment]
@sembrestels Luckily we don't have to go back in the past to improve the malleable systems we've created and put in place. We have the here-and-now to learn from our previous decisions and to improve upon the systems we put in place. 

That commitment to excellence by improvement, to community-focused values and to courage with vision and insight is the very heart of the TEC. 

We as humans exist in an ever-evolving relationship with the many systems we create and live by. They will never be "perfect", and/but we will continually strive to improve them. That is the nature of moving forward, of ingenuity, of creativity and of valuing the community, which exists and thrives only through our collective being.

**Comment by LinuxIsCool** [comment]
This proposal is lazy. It's the easy way out. It discourages the consideration of the entire space of possible praise augmentations. The memes are candy. Are we rotting our teeth before we are born? Rusting our infrastructure before it is deployed? If the praise system is to be improved, then NOW is the time to improve it. 

There are many proposals that do not even modify the current praise data in any way. For example @GriffGreen's solution in which we simply throw a big praise party to praise all the TE rockstars that we cherish. This is using the system itself to heal itself, anti-fragility by self-repair. #2 

Also consider @tamarandom's solution for praise categorization, which says, not to change past praise data, but adjust the way that we allocate praise in the future, say, giving a fixed 1% of praise weight to retweets, and 3% praise weight to meeting attendance. This would mean a retweet would be roughly 0.09 IH and attending a meeting would be roughly 0.2 IH. This sounds amazing to me, and allows us to consider how the other 96% of IH are allocated as well. #6

**Comment by sembrestels** [comment]
> Luckily we don't have to go back in the past to improve the malleable systems we've created and put in place

A malleable system is a weak system: it folds easily to the desires of people, it can't be trusted, or be predicted. If we create a community in which any previous agreements can be withdrawn for the sake of "self-improvement", then it will be easily manipulated by whoever has more support in each moment. Top-to-down solutions should not be part of our community values.

> This proposal is lazy.

Indeed. I wrote it quickly. Somebody had to agglutinate the people thinking that it's better to continue with the previous agreements. I hope other people can add better arguments than the ones I'm adding here.

**Comment by danelsuga** [comment]
A malleable system is democracy. What you are criticizing above is democracy. It is not top-to-down. 

Top-to-down would be allowing an imbalanced system that eventually permits an elite minority to decide for an entire community, maintaining a status quo that sidelines and harms the majority. 

Yes, indeed: “folding easily to the desires of the people” = democracy! 🥰

**Comment by danelsuga** [comment]
![7271166F-082A-4F9B-9283-6CDF835E0DB3](https://user-images.githubusercontent.com/81351744/124260151-a26e1000-db2f-11eb-93b3-207592e1de0b.png)

“Your economy, your choice.”

https://medium.com/token-engineering-commons/the-token-engineering-commons-hatch-your-economy-your-choice-354926284281

**Comment by danelsuga** [comment]
I feel like maybe there is some confusion in the interpretation of what is happening here? 

The TEC wants to be inclusive and fair. 

My feeling is that we cannot comfortably continue with a system where we know that is not happening. 

❤️
