### ISSUE TITLE
🚫👽 No Abnormal Intervention 👽🚫  75% Governance Rights returned to paid contributors via vote Post-Hatch & Praise Party for TE Rockstars

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/IH-intervention#2]
### What interventions are being proposed? 

I suggest we avoid any abnormal interventions to the Impact hours distribution but suggest 2 interventions that can be done via the system as is.

# 1 - Governance Giveback - All the people that were deducted IH for being paid get 75% of the TEC that they would have gotten as locked TEC that can never be sold but still used as governance rights 

So if someone had 100 IH deducted for being paid, they would get 75 IH worth of TEC tokens locked in a smart contract that they could use for Governance but would never be able to sell. 

This would be possible after the Hatch has ended, when we know the TEC/IH exchange rate, TEC token holders would need to ratify this via a vote and then this would be included in the Commons Upgrade and we would find a technical solution to make this happen (there are many solutions). 

# 2 - TE Praise Party - Throw a praise party for Token Engineers that have contributed to the space and give extra IH in the last Praise Quant

The TE's receiving Praise need to be onboarded into our discord (Which should be a requirement for anyone that we give tokens to!) and then we Dish them good praise and then for the last praise quant we give lots of IH to these critical thought leaders and badasses in the TE Community.

### What is the reasoning?

# 1 - Governance Giveback

The Impact Hours distribution is actually pretty fine, it’s not bad enough to require an intervention of any serious degree that can’t be done using the normal channels, so probably no abnormal intervention is needed with one exception, the core contributors that should have been paid lose governance rights because of their financial reward. **This is bad for the Commons**, these contributors have a deep understanding of the inner workings of the system and how things evolved to get to launch. This context is very valuable for the DAO to have when voting on proposals, especially related to DAO operations and upgrades. 

In the financial dimension, 85% actually worked out well. 

Some statistics:

- Most core contributors working full time for the TEC earn around 40 Impact Hours each week before their deduction… Then they would be deducted 34 IH, only getting 6 IH for the 2 week period. (This varied a lot, but 40 is about average)

- Full time contributors get 1400 DAI for that period (100/calendar day is the full time pay rate 19 dai/hour is the default part time hourly rate).

- This would mean they effectively traded 1400 DAI now for 34 IH worth of TEC later, or ~41 Dai/IH

- Given our current parameters 41 Dai/IH is about how much an Impact Hour is worth if we raise 1.3 million wxDai.

<img width="392" alt="Screen Shot 2021-06-21 at 4 39 54 PM" src="https://user-images.githubusercontent.com/14945613/122852588-2d216480-d311-11eb-94de-634cfe347591.png">

This is a fair outcome from a financial perspective. The people who chose to take a risk and contribute for only impact hours may receive more or less than the people who chose to reduce their risk and take a reliable salary depending on the success of our Hatch. This is the ideal outcome.

But the intertwining of money and governance rights is not ideal. Luckily, we are working with a very extensible system and we can create a technical solution that can give governance rights without affecting the monetary rewards or the bonding curve. 

One way would be to mint tokens that are locked in an infinite vesting contract and we can adjust the Virtual Supply parameter to make the bonding curve ignore the minted tokens that can never be sold but can be used for voting. 

Another way being discussed is to create a nontransferable token that could be used along side the TEC token for Governance in the Voting Apps in the TEC.

This will take some research to figure out the best technical solution. If this proposal is chosen, then the research to figure the  cleanest technical solution to implement that will fit the requirements will be chosen by the Commons Swarm.

I do not think they should get a full 100% of these impact hours because part of the deal when they decided to be paid was that they were giving up governance rights, so we should remain true to that initial understanding, **only mitigating it for the good of the Commons**. Also these core contributors have a lot of social influence as well which will likely more than compensate for the 25% of direct governance rights that they are not getting. 

# 2 - TE Praise Party

Determining who in the Token Engineering Field deserves to be rewarded with Impact Hours is a very difficult task, and is unlikely to be agreed upon easily. Who wants to make the list? How do we justify why one person gets more than another? This is not easy! But we are in luck! The praise process as it is already organized is a perfect way to do this, in fact it is intended for this exact purpose!

The Praise with the largest IH reward is this one: 

<img width="932" alt="Screen Shot 2021-06-21 at 8 09 50 PM" src="https://user-images.githubusercontent.com/14945613/122852125-686f6380-d310-11eb-8d75-a106eb86390e.png">

Here are several others that are hefty TE Praises:

<img width="1084" alt="Screen Shot 2021-06-21 at 8 31 13 PM" src="https://user-images.githubusercontent.com/14945613/122854621-4841a380-d314-11eb-97ec-c5a5397ac807.png">
<img width="1105" alt="Screen Shot 2021-06-21 at 8 43 38 PM" src="https://user-images.githubusercontent.com/14945613/122855062-ed5c7c00-d314-11eb-929b-96b9488ddc5f.png">
<img width="1187" alt="Screen Shot 2021-06-21 at 8 36 47 PM" src="https://user-images.githubusercontent.com/14945613/122855064-edf51280-d314-11eb-8692-93adb48bd26d.png">
<img width="1089" alt="Screen Shot 2021-06-21 at 8 45 47 PM" src="https://user-images.githubusercontent.com/14945613/122855057-eb92b880-d314-11eb-942a-1259dfc8716b.png">--- 

The precedent is set already that we can reward Token Engineers for their past work with Praise, the only requirement is that they join our discord (reasonable if we are giving them governance they need to have access to this key source of information) and that some one explain why they deserve to be rewarded. 

All we need to do is just agree that we will give a lot of IH in the last Distro where we collect the praise, we usually do ~1200 (and about 1/2 is taken away from paid contributors) maybe this batch we make it double that assuming we have engagement with listing out all the great TE work that has been done already... And of course it would be great to get a TE aware person to come to a quant to help judge how to distribute.... but also people can just be very explicit in dishing praise, even asking straight up for an IH amount if they want! 

I can't think of a better way to reward the TE Community for their work.

🤔 Take a look at [this forum post](https://forum.tecommons.org/t/pre-hatch-impact-hours-distribution-analysis/376/50?u=liviade) if you have any questions.

🗳 When you are finished writing, head over to [TokenLog](https://tokenlog.xyz/TECommons/TokenLog-SoftGov) and vote for your favorite proposals! 

📆 This voting session ends on Thursday, July 1 at 2pm EST / 8pm CET, the start of the weekly TEC Community Call.

**Comment by GriffGreen** [comment]
<a href="https://imgflip.com/i/5evsik"><img src="https://i.imgflip.com/5evsik.jpg" title="made at imgflip.com"/></a><div><a href="https://imgflip.com/memegenerator">from Imgflip Meme Generator</a></div>

**Comment by jessicazartler** [comment]
![fix-itself](https://user-images.githubusercontent.com/43972522/123883439-08cc1600-d917-11eb-8d6a-71e86fa758d5.jpg)

**Comment by MrsBadgerface** [comment]
Hey @GriffGreen Acknowledging and appreciating ' **the core contributors that should have been paid lose governance rights because of their financial reward. This is bad for the Commons, these contributors have a deep understanding of the inner workings of the system and how things evolved to get to launch. This context is very valuable for the DAO to have when voting on proposals, especially related to DAO operations and upgrades**.' It makes immense sense to me to ensure that members with the greatest context have an impact on any next steps, especially in this field and in such early days.

**Comment by LinuxIsCool** [comment]
Rockstar Nomination:

![image](https://user-images.githubusercontent.com/31582215/124198152-f40d9080-da84-11eb-8180-a6ff799140e3.png)

https://twitter.com/wor

https://www.grassrootseconomics.org/research

**Comment by danelsuga** [comment]
Yes, I strongly appreciate this gesture to restore governing rights. This particular issue of governance vs. monetary compensation is a wonderful example of the (unintended) shortsightedness of the initial implementation of the praise system. It fully demonstrates that the praise system needs modification to accommodate the actual circumstances as we now see them. 

(Just a tiny mention that I would have used different language from "abnormal", as that suggests what is currently in place is "normal", which is not actually accurate. The praise system has nothing to do with "normal" and "abnormal", and IH intervention reflects simply "what is in place" and "changing what it is in place". In lieu of "abnormal", then, I would suggest "radical" or "drastic", etc. to emphasize the depth of change as opposed to a judgment on its quality or character.)

Thanks, @GriffGreen!

❤️

**Comment by danelsuga** [comment]
Yes, I strongly appreciate this gesture to restore governing rights. This particular issue of governance vs. monetary compensation is a wonderful example of the (unintended) shortsightedness of the initial implementation of the praise system. It fully demonstrates that the praise system needs modification to accommodate the actual circumstances as we now see them.

(Just a tiny mention that I would have used different language from "abnormal", as that suggests what is currently in place is "normal", which is not actually accurate. The praise system has nothing to do with "normal" and "abnormal", and IH intervention reflects simply "what is in place" and "changing what is in place". In lieu of "abnormal", then, I would suggest "radical" or "drastic", etc. to emphasize the depth of change as opposed to a judgment on its quality or character.)

Thanks, @GriffGreen!

❤️
