### ISSUE TITLE
paid contributors rebalanced and praise party to TEs with an education bonus 

### ISSUE THREAD

**Issue by liviade1** [CommonsBuild/IH-intervention#3]
### What interventions are being proposed? 
1-  My opinion is that Twitter and attending meetings were overcompensated considering the average IH for Twitter was 0.54 and the average for meetings was 1.14.
I can’t think of a fair way to redistribute the weight between categories. I believe praising attendance was a large building block of our culture but that the quantification was heavy on the rewards. I would suggest that moving forward, retweets aren’t praised and meetings are rewarded by SourceCred or quantified more lightly. 

2 - Below is a list of all contributors paid by the Commons Stack, Giveth, General Magic and the Commons Swarm who are getting an IH deduction. I would like to propose that: 

1. Contributors who didn’t have their primary jobs workload affected by TEC work have their full IH restituted; 
2. Contributors who did have their primary job workload slightly merged with the TEC get a deduction of 20%; 
3. Contributors who had about half of their primary job workload merged with the TEC get a deduction of 40%;
4. Contributors who have most of their workload merged with the TEC get a deduction of 60%; 
5. Contributors who have the TEC as their full workload get a deduction of 70%. 

I talked to a few people on this list to try getting clarity about their workloads and agreements but there still might be wrong assumptions, so please feel free to contact me.  

jeffemmett Gets paid by the Commons Stack. Only a small part of his workload is TEC - 2. 20%
Currently has 85% deduction

divine_comedian Gets paid by General Magic, half of his workload is for the TEC - 3. 40% 
Currently has 50% deduction

iviangita Gets paid by the Commons Stack. Half of her workload is TEC - 3. 40%
Currently has 50% deduction

GriffGreen Gets paid by the Commons Stack.  About half of his CS work is merged with the TEC - 3. 40%   
Currently has 85% deduction

chuygarcia92 Gets paid by the Commons Stack and his full workload is TEC - 5. 70%
Currently has 85% deduction 

markop gets paid by General Magic and a minor part of his work is merged with the TEC - 2. 20% 
Currently has 50% deduction

VitorMarthendal Gets paid from General Magic and about half of his workload is TEC - 3. 40%
Currently has 50% deduction 

JuankBell Gets paid by the Commons Stack to support the TEC - 5. 70%
Currently has 85% deduction 

fabiosmendes Gets paid from General Magic and about half of his workload goes to the TEC - 3. 40%
Currently has 50% deduction

Tam2140 Gets paid by the Commons Stack and about half of her workload is TEC  - 3. 40%
Currently has 85% deduction

Suga#8514 Gets paid by the Commons Stack to support the TEC - 5. 70% 
Currently has 85% deduction

mateodaza Gets paid by Giveth and his paid work isn’t merged with the TEC - 1. Full IH
Currently has 50% deduction

sembrestels Gets paid by the Commons Swarm to support the TEC - 5. 70% 
Currently has 85% deduction 

fabimol Gets paid occasionally by the Commons Swarm to support the TEC and not all his work is covered. 3. 40%
Currently has 50% deduction

Laurenluz Gets paid by Giveth and her paid work isn’t merged with the TEC- 1. Full IH 
Currently has 50% deduction 

geleeroyale Gets paid by the Commons Swarm for to occasionally help with the TEC - 3. 40% 
Currently has 50% deduction 

liviade Gets paid by the Commons Stack and most of her workload is merged with the TEC - 4. 60% 
Currently has 85% deduction 

naynaysoo Gets paid by the Commons Stack and most of his workload is focused on the TEC - 4. 60% 
Currently has 85% deduction 

Vyvy-vi#5040 Gets paid by the Commons Stack to support the TEC - 5. 70%
Currenlty has 85% deduction 

vegayp Gets paid by the Commons Stack to support the TEC - 5. 70%
Currently has 85% deduction 

aminlatifi Gets paid by Giveth and his workload isn’t affected by the TEC- 1. Full IH 
Currently has 50% deduction 

paulo_c2d Gets paid by the Commons Swarm to support the TEC - 5. 70% 
Currently has 85% deduction

JessicaZartler Gets paid by the Commons Stack and her work is minorly merged with the TEC since February. Propose restoring to  2. 20% since then.  
Currently has 85% deduction 

atacas Gets paid by the Commons Stack and his work doesn’t merge with the TEC - 1. Full IH 
Currently has 50% deduction

Krisjones Gets paid by the Commons Stack and his work doesn’t merge with the TEC - 1. Full IH 
Currently has 85% deduction 

knobsDAO Gets paid by the Commons Stack and his work doesn’t merge with the TEC - 1. Full IH
Currently has 85% deduction 

3 - Similar to Griff’s proposal, I suggest we have a praise party for critical TE members. I additionally suggest we add how much IH we think they should receive to help with the praise quantification and also that we make a list with some of their contributions to the TE ecosystem and share them on tweets and on a blog post as an educational initiative. 

4 - I love the idea of a UBI but it’s something that needs more thinking in my opinion. I don’t see how distributing UBI now could help with the problem sets that were initially raised, especially with giving better rewards to TEs and improving the governance distribution. 

...

### What is the reasoning?

...

--- 

🤔 Take a look at [this forum post](https://forum.tecommons.org/t/pre-hatch-impact-hours-distribution-analysis/376/50?u=liviade) if you have any questions.

🗳 When you are finished writing, head over to [TokenLog](https://tokenlog.xyz/TECommons/TokenLog-SoftGov) and vote for your favourite proposals! 

📆 This voting session ends on Thursday, July 1 at 2pm EST / 8pm CET, the start of the weekly TEC Community Call.

**Comment by Zeptimus** [comment]
![image](https://user-images.githubusercontent.com/74430951/123853492-ce19ac00-d91d-11eb-9ab2-ebfc64b0278e.png)

**Comment by jessicazartler** [comment]
![image](https://user-images.githubusercontent.com/43972522/123883364-de7a5880-d916-11eb-9e4f-6d01a08f3f89.png)

**Comment by danelsuga** [comment]
Thank you, @liviade1! I appreciate your attempt to reimagine a more correct distribution. It is evident change is needed, and simply because that change will be difficult to sort out does not mean it shouldn't happen!

❤️

**Comment by MrsBadgerface** [comment]
Hey @liviade1 I can only imagine the time you've spent here going through so many individual situations and looking to work out what's fair for each of them and I would fully support tweets (and meeting attendance) getting a smaller amount of IH.
