### ISSUE TITLE
🥧 Sharing is Caring 🥧 #3 Fork + 7IH UBI

### ISSUE THREAD

**Issue by jessicazartler** [CommonsBuild/IH-intervention#4]
### 1. Does this proposal address that some categories may be under rewarded and others over rewarded?

Yes

### 2. Does this proposal address that paid contributors have had a 50-85% reduction to their total number of impact hours?

Yes

### 3. Does this proposal address that foundational members of the Token Engineering Community may lack recognition for their less visible work?

Yes

### 4. Does this proposal address the distribution of impact hours in relation to equality metrics such as the Gini Coefficient?

Yes

### What interventions are being proposed? 

**This is a fork of Livia's proposal #3 + 7IH UBI** 
https://github.com/CommonsBuild/IH-intervention/issues/3

1. **I agree with Livia that meetings/tweets were rewarded too highly**. This may have been good for an initial few months to jumpstart the community but attending meetings should not be rewarded more highly than actually doing and coordinating the work, and all of the other buckets on the list. There is sadly, no easy way to fix this so +1 with Livia **going forward that this should be re-weighted.**

2. **Taking away 85% of Impact Hours for people who were not paid to work on TEC is not fair.** That would be like taking away 85% for everyone who gets paid by any project.. just because these projects are close to TEC, shouldn't mean that we punish these people for getting paid to do non-TEC work. I love Livia's solution and suggestions for restoration. **This also supports in having better distribution overall to make these adjustments.**

3. This may address some issues with TE contributions (thought I think this has been somewhat remedied recently), however **it does not address the core issue and poor distribution** and that the top praise holder has x2 that of 5th place, x3 #9 spot, x4 the #12 spot, x10 spot #40 ... did the top praise holder do 4x the work, or are they 4x more valuable than the top 12 "active" contributors? **Are they 10x more valuable than the top 40 most active contributors?** For me, this is the core of the issue (in addition to some askew rankings of folks who have high scores for attending meetings (x2 of people who worked much harder - which is too "sensitive/personal" to discuss) and **why I am suggesting an additional UBI adjustment.**

**4. I propose a UBI to support more equitable distribution in the overall system as I don't believe anyone's work should be valued 2,3,4 or 5x as much as the top active contributors.** 

**PROPOSAL:** **I am suggesting adding 7 impact hours to everyone on the list as a starting point.** This brings the GINI* co-efficient from 0.42 to 0.39 for the top 20% of the list, which is 80 contributors and should cover the majority of stakeholders we are concerned about, while not getting drawn out by the longtail of smaller contributors. In addition to improving distribution, **this will also give more incentive to people who have fractions of Impact Hours at the bottom to participate**. Why would they go through the trouble to join the hatch to claim one or two hours - but perhaps they would for 10. Seven Impact Hours is the equivalent of going to about six meetings or RTing 13x - it's a small gift for potentially a bigger upside if those folks are given a little more stake, they will be more likely to participate. This brings the 3IH tier (threshhold of Hatcher Outreach) to 10IHs. **(And who doesn't like the number 7?)**

* Note: Some people are saying GINI isn't applicable, but I haven't heard other suggestions for measuring equity in distribution. I also don't think we should set the bar at projects with worse distribution and standing oligarchical crypto projects, we should raise the bar of our economy to the standard of GINI, which is [used by the UN](https://unstats.un.org/sdgs/report/2020/goal-10/) to measure whether or not economies are equitable. The point is, we know the distribution is poor, so let's apply at least a small adjustment, so the distribution of value is at least slightly more equitable.

### What is the reasoning?

I would like to propose much more, but sadly, not sure if the community would vote for that, so I am suggesting a small adjustment. **Sharing is caring**. It's not about "taking away hours" - the top of the list and the 1% whales having more, actually takes away from other top active contributors who did just as much work - **NO ONE did 2,3,4,5 or 6x the amount of work, or is 6x more valuable than other top contributors.** 

_**We should care more about the collective and equitable distribution, than our own personal gain if we are truly in alignment with the mission of this community and commons.**_

--- 

🤔 Take a look at [this forum post](https://forum.tecommons.org/t/pre-hatch-impact-hours-distribution-analysis/376/50?u=liviade) if you have any questions.

🗳 When you are finished writing, head over to [TokenLog](https://tokenlog.xyz/TECommons/TokenLog-SoftGov) and vote for your favourite proposals! 

📆 This voting session ends on Thursday, July 1 at 2pm EST / 8pm CET, the start of the weekly TEC Community Call.

**Comment by jessicazartler** [comment]
![image](https://user-images.githubusercontent.com/43972522/123883646-737d5180-d917-11eb-9974-94a33789cba0.png)

![girl look ubi](https://user-images.githubusercontent.com/43972522/123836126-56c12980-d8d7-11eb-8e51-eca2a333d206.jpg)

**Comment by jessicazartler** [comment]
![ubi-baby](https://user-images.githubusercontent.com/43972522/123836157-5de83780-d8d7-11eb-873a-ecd4c03bf68b.jpg)

**Comment by jessicazartler** [comment]
![oprah](https://user-images.githubusercontent.com/43972522/123836168-62145500-d8d7-11eb-9c73-70a783342970.jpg)

**Comment by jessicazartler** [comment]
![yoda](https://user-images.githubusercontent.com/43972522/123836184-680a3600-d8d7-11eb-8681-fab70df1cf16.jpg)

**Comment by jessicazartler** [comment]
![eqyal](https://user-images.githubusercontent.com/43972522/123836231-75bfbb80-d8d7-11eb-8666-2edf7864cd1a.jpg)

**Comment by jessicazartler** [comment]
![Draw-25](https://user-images.githubusercontent.com/43972522/123836252-7d7f6000-d8d7-11eb-9b8d-7dbf7e835f2f.jpg)

**Comment by jessicazartler** [comment]
![Whoa](https://user-images.githubusercontent.com/43972522/123836312-8ff99980-d8d7-11eb-8e00-66b363792f2c.jpg)

**Comment by jessicazartler** [comment]
![slap](https://user-images.githubusercontent.com/43972522/123836383-a4d62d00-d8d7-11eb-8d21-f0c4bfe9a72a.jpg)

**Comment by jessicazartler** [comment]
![share](https://user-images.githubusercontent.com/43972522/123836434-b1f31c00-d8d7-11eb-86fe-ee8144adf2bc.jpg)

**Comment by jessicazartler** [comment]
![yoda](https://user-images.githubusercontent.com/43972522/123836184-680a3600-d8d7-11eb-8681-fab70df1cf16.jpg)

**Comment by sembrestels** [comment]
![1fkygd](https://user-images.githubusercontent.com/931684/123852618-ce657780-d91c-11eb-95b3-fbed62692f38.jpg)

**Comment by Zeptimus** [comment]
![image](https://user-images.githubusercontent.com/74430951/123853451-c35f1700-d91d-11eb-923a-3b79c5575d86.png)

**Comment by sembrestels** [comment]
![war](https://user-images.githubusercontent.com/931684/123854301-d45c5800-d91e-11eb-81b6-ed49527a0768.jpeg)

**Comment by Zeptimus** [comment]
![image](https://user-images.githubusercontent.com/74430951/123874113-e5fe2980-d937-11eb-86d5-3e4987672862.png)

**Comment by MrsBadgerface** [comment]
Hey @jessicazartler I felt the depth of your care about equitable and just spaces when you shared about this last night, and I feel that again reading this. I also feel deeply that we have an opportunity in these newer economies and communities to make the choice to not recreate systems and structures already in the world but to take the risk to be brave and do everything we can to create spaces that move closer towards those equitable and just ideals. So, nothing profound that I can add here but just that I appreciate your care and your commitment to commons care.

**Comment by jessicazartler** [comment]
Thank you Anna-Marie for your participation and feedback. I very much appreciate your point of view and your feelings about what we are trying to create. I appreciate everyone's point of view. Glad we can have dialogue and processes to hear everyone's voices and engage in voting processes and a decision space that everyone agreed on to come to a resolution. We had a process and didn't know when we began, what it would result in as it was an experiment. It's hard to agree to something unknown, and now that we know more clearly - we have a choice. Some have more, and I hope they will choose to share with others who poured equal amounts of blood, sweat, tears and heart into building this commons and make a statement to the wider crypto space that wider and more equitable distribution, and sharing in value and wealth generation is why we are here. 🙏 I would gladly share my Impact Hours with others to have more equal "slices" of the "pie."

**Comment by danelsuga** [comment]
Thank you, @jessicazartler! No intervention moves the TEC in the absolute wrong direction on numerous levels. We are here for something else!  

Yes, yes, yes, @MrsBadgerface! 
"I also feel deeply that we have an opportunity in these newer economies and communities to make the choice to not recreate systems and structures already in the world but to take the risk to be brave and do everything we can to create spaces that move closer towards those equitable and just ideals."

❤️

Just. a quick note on the Gini coefficient: 

@jessicazartler, Octopus made a useful video last week where he applied several methods: https://www.youtube.com/watch?v=MlGoYXk5x8o

He explains: “These are calculations requested by the community. None of the terms have any value judgment. For example, it is not necessarily the case that a more decentralized distribution is better or fairer. These interpretations do not necessarily reflect the work that was done by people, and due to the fact that there are multiple competing measures/issues (including compensation rates, tasks that varied in assessed Praise value from week to week), the data is intrinsically complicated, and no one number or measurement can capture the aspects of it.” He also clarified the technical definition of “decentralization” as being when a collective body has “a large number of points of failure”.
