### ISSUE TITLE
Bad for the Commons is bad for us all, restore 40% of deleted earned Impact Hours

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/IH-intervention#6]
### 1. Does this proposal address that some categories may be under rewarded and others over rewarded?

No retroactively / Yes for future praise quantifications 

### 2. Does this proposal address that paid contributors have had a 50-85% reduction to their total number of impact hours?

Yes

### 3. Does this proposal address that foundational members of the Token Engineering Community may lack recognition for their less visible work?

No

### 4. Does this proposal address the distribution of impact hours in relation to equality metrics such as the Gini Coefficient?

No

### Preamble 

The majority of us are not engineers but we are collectively undertaking this mission to advance a novel and nascent form of engineering that we all believe has real potential to create a more ethical and just world. With that in mind, I thought it worth sharing the Engineers’ Creed. The longer [Code of Ethics](https://www.nspe.org/resources/ethics/code-ethics) is good too but the Creed is nice and concise.

As a Professional Engineer, I dedicate my professional knowledge and skill to the advancement and betterment of human welfare.

I pledge:
- To give the utmost of performance;
- To participate in none but honest enterprise;
- To live and work according to the laws of man and the highest standards of professional conduct;
- To place service before profit, the honor and standing of the profession before personal advantage, and the public welfare above all other considerations.

A decision not to intervene in a system that, unintentionally, resulted in some serious flaws that are bad for our Commons feels like the antithesis of an engineering spirit. “It’s broken but don’t fix it” does and should create a cognitive dissonance.

### What interventions are being proposed? 

**_Does this proposal address that some categories may be under rewarded and others over rewarded?_**

Not retroactively but going forward, yes, I propose the following as an immediate solution. We have a set percentage of total % of IH for retweets and for attending calls. 

What does that look like? It’s a very simple solution that can be implemented in the next Praise quantification. Let’s take an example,

We say:
- Retweets are allocated 1% of total IH for that session
- Attending calls are allocated 3% of total IH for that session

We have:
- About 1200 IH allocated per session

That means:
- 12 IH would be divided among all retweet praise (in the sesion of May 7th there were 134 retweets, that would mean 0.09 IH are allocated per retweet praise). We cannot measure the real impact of these automated retweet praises and they all use the same exact phrasing which makes them trivial to separate from the rest of the Praise. One-off, impactful tweet praise will not fall into this bucket and so can be subjectively weighted by the quantifier. 
- 36 IH would be divided among call praise  (in the May 7th session there were 183 calls that have “joining” and for this back of the envelope calculations, let’s use that. This means that each call attendance would be awarded 0.20 IH). In order to achieve this, the Stewards would use an easily parsable string in their “attending call” praise. Simple.
- Bonus! Quantification efficiency. In the May 7th case, 38% of the xls rows would be automatically quantified by this system. The current 2+ hours of typing numbers into a cell after cell of the spreadsheet will be nearly 40% less painful! 
- Bonus! The act of passively attending a call is still rewarded but not disproportionately to specific praise given for concrete pieces of impactful contributions. 

Why am I not proposing a retroactive intervention? The data set, like any data set not designed with future data analysis in mind, is not clean enough to do this in any legitimate way I can see other than going back and manually inspecting each praise and tagging into a category. To undertake this will require agreement on categories, category weights and then the herculean effort to manually inspect much if not all of the data set. The possible results do not merit the time or effort that would be required to do this with a sufficiently high level of quality. 

**_Does this proposal address that paid contributors have had a 50-85% reduction to their total number of impact hours?_**

The root problem is that Impact hours are being conflated with compensation. Praise is designed to promote a culture of gratitude and to showcase invisible work. It works very well for that. We see clearly the model break when employed as an alternative compensation method.

As Griff underscores in #2 : “**This is bad for the Commons**, these contributors have a deep understanding of the inner workings of the system and how things evolved to get to launch. This context is very valuable for the DAO to have when voting on proposals, especially related to DAO operations and upgrades.”

I am making this proposal intentionally modest in the hopes that the Stewards, active TEC Community and wider Impact Hour and CSTK holders will recognize that doing nothing is indeed a terrible decision for the TEC and that a modest intervention will be palatable enough to see this intervention passed.

The proposal is to **restore 40% of deleted earned Impact Hours**. 

What does that look like? 
- For someone that has had 50% of their IH deleted, they will now receive 70% of their IH instead of 50%.
- For someone that has had 85% of their IH deleted, they will now receive 49% of their IH instead of 15%.
- The below chart shows current percentages in yellow vs. proposed percentages in blue.

![Screen Shot 2021-06-30 at 1 11 41 PM](https://user-images.githubusercontent.com/703624/123951112-b76a6800-d9a4-11eb-84c7-9390ecc165a1.png)

These are the contributors that are impacted. 

![Screen Shot 2021-06-30 at 1 14 12 PM](https://user-images.githubusercontent.com/703624/123951431-129c5a80-d9a5-11eb-9b74-a1f9e93c4c3c.png)

Conflating monetary value and governance power is, of course, the glaringly obvious oopsie but hindsight sometimes works like that. Ok. Fortunately, there is one opportunity to now correct for the uncovered flaws in the model. That it wasn’t inspected or this wasn’t well thought through before is not a reason not to fix what's broken now when the opportunity presents itself.  Even if only in a minor, token way being proposed here. 

Then there is the question of the dubiously wide net cast. For example: Griff, Livia and myself are very active in the day to day of the TEC. If there was ever any reason to justify deleting 85% of IH, it could be made for us but Jeff, Dan and Kris have full time jobs and full time work at Commons Stack and participate in the TEC not because it is part of their job but 
because they want to. Just like all the other contributors here who are receiving their full earned Impact Hours.

My proposal does not address this individual by individual like Livia’s #3 because I am favoring simplicity with one action applied to all impacted. Whether, when and how deductions should be applied going forward is a discussion outside the scope of this proposal but a commitment to those future discussion does not absolve one of the responsibility to act now. 

If you’ve gotten this far, 🤗  thanks for reading! 

### What is the reasoning?
(reasoning included above)

---

🤔 Take a look at [this forum post](https://forum.tecommons.org/t/pre-hatch-impact-hours-distribution-analysis/376/50?u=liviade) if you have any questions.

🗳 When you are finished writing, head over to [TokenLog](https://tokenlog.xyz/TECommons/TokenLog-SoftGov) and vote for your favourite proposals! 

📆 This voting session ends on Thursday, July 1 at 2pm EST / 8pm CET, the start of the weekly TEC Community Call.

**Comment by MrsBadgerface** [comment]
Hey @tamarandom Much appreciation for how you've broken this down so clearly.  I can see how the current system seems to be set up to dis-favour the very people that give it time and care and I can see the sense from a systems change perspective of nudging where we're at with simple, clear small steps.

**Comment by danelsuga** [comment]
Thank you, @tamarandom, for this great and meaningful effort to modify a broken system without being too disruptive. Were we able only to wish that the radically anti-traditional-establishment MVV of the TEC based on equality and inclusion could accept more (of what's best for the commons)! ❤️

**Comment by sembrestels** [comment]
> A decision not to intervene in a system that, unintentionally, resulted in some serious flaws that are bad for our Commons feels like the antithesis of an engineering spirit. “It’s broken but don’t fix it” does and should create a cognitive dissonance.

Unfortunately, there are many times that we face problems that is better not to fix, because fixing them create greater problems. In this talk we can see [Andreas Antonopoulos giving an example](https://youtu.be/XJnYB78pcHM?t=1015): even changing three lines of code in the bitcoin protocol to fix multisigs is worst than the problem that they cause. The talk was given in the context of the Bitcoin / Bitcoin Cash fork, and in some way it resembles the current discussion.

**Comment by LinuxIsCool** [comment]
To summarize this intervention:
1. For future praise - create a fixed 4% IH allocation for re-tweets and attending meetings. This would make a re-tweet worth roughly 0.09 IH and attending a meeting roughly 0.2 IH
2. Return 40% of deducted impact hours back to the workers

**Comment by Jeff-Emmett** [comment]
> > A decision not to intervene in a system that, unintentionally, resulted in some serious flaws that are bad for our Commons feels like the antithesis of an engineering spirit. “It’s broken but don’t fix it” does and should create a cognitive dissonance.
> 
> Unfortunately, there are many times that we face problems that is better not to fix, because fixing them create greater problems. In this talk we can see [Andreas Antonopoulos giving an example](https://youtu.be/XJnYB78pcHM?t=1015): even changing three lines of code in the bitcoin protocol to fix multisigs is worst than the problem that they cause. The talk was given in the context of the Bitcoin / Bitcoin Cash fork, and in some way it resembles the current discussion.

Not fixing this problem also comes with it's own dangers, @sembrestels. Among them:
- deterring Token Engineers from participating in a community economy that doesn't value their inputs or labor 
- unabashedly dismissing necessary algorithmic policy steps (e.g. critical analysis of output data) in the interest of protecting the privilege of a few large token holders (who were the beneficiaries of a skewed IH distribution process)
- relegating the TEC to be as oligarchical and inequitable as legacy protocols, despite the community sentiment to "end the technocracy".  What I am most interested to see in this process, is whether the TEC is willing to walk its talk...

Great proposal, @tamarandom!
