### ISSUE TITLE
Extend Voting One Week. Deadline for Submissions Thursday July 1st. Deadline for Voting July 8th. 

### ISSUE THREAD

**Issue by LinuxIsCool** [CommonsBuild/IH-intervention#7]
# Extend Voting

Impact hours is a huge deal for everyone in this economy. Some incredible proposals have been submitted. Personally, I would  like to really take the time to read them all in detail and have some dialogue in the comments. 

I'm going through all of the proposals now to understand what they are saying, add comments to them, and ultimately make my own proposal. This will take me a few hours, and I think that everyone should have the right to go through this process. 

I think this is reasonable for the hatch timeline. We have been patient up to this point with all of the working groups and all of the incredible work that has been done. I think we should give a similar space and gratitude to the process that is unfolding between labs, soft gov, comms, omega, and the community as a whole to facilitate this process of introspection. Tamara nailed it with the Engineers Creed #6 . If we are to consider ourselves engineers, then we all have a responsibility to question the safety of the systems that we are co-designing. 

I'll be voting for this proposal. I hope it passes.

**Comment by danelsuga** [comment]
While I appreciate this initiative and would otherwise vote for it, I don't think it is wise (or permissible) to raise a distinctly different topic within a vote on something else entirely. 

I am all for approving this request, but it cannot happen within the vote for another topic.

Thank you, @LinuxIsCool, for this important, radical voice.

**Comment by LinuxIsCool** [comment]
You're right @danelsuga . I like how @jessicazartler put it in discord, this proposal is outside of the decision space.

Meanwhile, I feeling that I am accomplishing the following: 
* Stress testing the system
* Signalling to the community
* Buying myself at least a little bit of time.

**Comment by LinuxIsCool** [comment]
Closing this to release the votes.
